services:
  # App
  app:
    env_file:
      - ../../api/.env
    build:
      context: ../../api/
      dockerfile: Dockerfile
      target: laravel
    environment:
      - DB_DATABASE=/var/www/database/database.sqlite
      - DB_FOREIGN_KEYS=true
    container_name: laravel_api
    restart: unless-stopped
    ports:
      - "9000:9000"
    working_dir: /var/www
    volumes:
      - ../../api/:/var/www
      - ../api/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ../../api/:/var/www
      - ../api/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge
